; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define ClevyExePath "..\Win32\Release\Clevy.exe"
#define RsttsDllPath "..\Win32\Release\librstts-2.dll"

#include "Common.inc"

[Setup]
OutputBaseFilename=ClevyDyscover_x86
