//
// Keys.cpp
//

#include "Keys.h"

enum KeyTranslationFlags {
    //NoModifiers = 0,
    KTF_NoFlags = 0,
    KTF_Shift = 1,
    KTF_Ctrl = 2,
    KTF_Alt = 4,
    KTF_CapsLockActive = 8,
    KTF_CapsLockInactive = 16,
    KTF_SpeakSentence = 32,
};

enum class CapsLock
{
    Ignore,
    Active,
    Inactive,
};

struct KeyTranslationEntry
{
    // Inputs
    Key input;
    //bool shift;
    //bool ctrl;
    //bool alt;

    // Flags
    KeyTranslationFlags flags;

    // Outputs
    std::vector<KeyStroke> output;
    std::string sound;

    // Triggers
    bool speak_sentence;

    // Additional options
    CapsLock capsLock;
};

#if defined __LANGUAGE_NL__
static const std::vector<KeyTranslationEntry> g_dutchDefault = {
    { Key::Esc, KTF_NoFlags, { { Key::Esc, KSF_NoModifiers } } },
    { Key::CapsLock, KTF_NoFlags, { { Key::CapsLock, KSF_NoModifiers } } },
    { Key::Up, KTF_NoFlags, { { Key::Up, KSF_NoModifiers } } },
    { Key::Down, KTF_NoFlags, { { Key::Down, KSF_NoModifiers } } },
    { Key::Left, KTF_NoFlags, { { Key::Left, KSF_NoModifiers } } },
    { Key::Right, KTF_NoFlags, { { Key::Right, KSF_NoModifiers } } },
    { Key::Backspace, KTF_NoFlags, { { Key::Backspace, KSF_NoModifiers } } },
    { Key::Space, KTF_NoFlags, { { Key::Space, KSF_NoModifiers } } },
    { Key::Enter, KTF_NoFlags, { { Key::Enter, KSF_NoModifiers } } },
    { Key::Tab, KTF_NoFlags, { { Key::Tab, KSF_NoModifiers } } },
    { Key::Dot, KTF_NoFlags, { { Key::Dot, KSF_NoModifiers } }, std::string(), true },
    { Key::Dot, KTF_Shift, { { Key::Dot, KSF_Shift } } },
    { Key::Comma, KTF_NoFlags, { { Key::Comma, KSF_NoModifiers } } },
    { Key::Comma, KTF_Shift, { { Key::Comma, KSF_Shift } } },
    { Key::One, KTF_NoFlags, { { Key::One, KSF_NoModifiers } }, "1.wav" },
    { Key::Two, KTF_NoFlags, { { Key::Two, KSF_NoModifiers } }, "2.wav" },
    { Key::Three, KTF_NoFlags, { { Key::Three, KSF_NoModifiers } }, "3.wav" },
    { Key::Four, KTF_NoFlags, { { Key::Four, KSF_NoModifiers } }, "4.wav" },
    { Key::Five, KTF_NoFlags, { { Key::Five, KSF_NoModifiers } }, "5.wav" },
    { Key::Six, KTF_NoFlags, { { Key::Six, KSF_NoModifiers } }, "6.wav" },
    { Key::Seven, KTF_NoFlags, { { Key::Seven, KSF_NoModifiers } }, "7.wav" },
    { Key::Eight, KTF_NoFlags, { { Key::Eight, KSF_NoModifiers } }, "8.wav" },
    { Key::Nine, KTF_NoFlags, { { Key::Nine, KSF_NoModifiers } }, "9.wav" },
    { Key::Zero, KTF_NoFlags, { { Key::Zero, KSF_NoModifiers } }, "0.wav" },
    { Key::One, KTF_Shift, { { Key::One, KSF_Shift } }, std::string(), true },
    { Key::Two, KTF_Shift, { { Key::Two, KSF_Shift } } },
    { Key::Three, KTF_Shift, { { Key::Three, KSF_Shift } } },
    { Key::Four, KTF_Shift, { { Key::Four, KSF_Shift } } },
    { Key::Five, KTF_Shift, { { Key::Five, KSF_Shift } } },
    //{ Key::Six, KTF_Shift, { { Key::Six, KSF_Shift } } },
    { Key::Seven, KTF_Shift, { { Key::Seven, KSF_Shift } } },
    { Key::Eight, KTF_Shift, { { Key::Eight, KSF_Shift } } },
    { Key::Nine, KTF_Shift, { { Key::Nine, KSF_Shift } } },
    { Key::Zero, KTF_Shift, { { Key::Zero, KSF_Shift } } },
    { Key::OpenBracket, KTF_NoFlags, { { Key::OpenBracket, KSF_NoModifiers } } },
    { Key::OpenBracket, KTF_Shift, { { Key::OpenBracket, KSF_Shift } } },
    { Key::CloseBracket, KTF_NoFlags, { { Key::CloseBracket, KSF_NoModifiers } } },
    { Key::CloseBracket, KTF_Shift, { { Key::CloseBracket, KSF_Shift } } },
    { Key::Semicolon, KTF_NoFlags, { { Key::Semicolon, KSF_NoModifiers } } },
    { Key::Semicolon, KTF_Shift, { { Key::Semicolon, KSF_Shift } } },
    { Key::Apostrophe, KTF_NoFlags, { { Key::Apostrophe, KSF_NoModifiers } } },
    { Key::Apostrophe, KTF_Shift, { { Key::Apostrophe, KSF_Shift } } },
    { Key::Backslash, KTF_NoFlags, { { Key::Backslash, KSF_NoModifiers } } },
    { Key::Backslash, KTF_Shift, { { Key::Backslash, KSF_Shift } } },
    { Key::Minus, KTF_NoFlags, { { Key::Minus, KSF_NoModifiers } } },
    { Key::Minus, KTF_Shift, { { Key::Minus, KSF_Shift } } },
    { Key::Slash, KTF_NoFlags, { { Key::Slash, KSF_NoModifiers } } },
    { Key::Slash, KTF_Shift, { { Key::Slash, KSF_Shift } }, std::string(), true },
    { Key::Equal, KTF_NoFlags, { { Key::Equal, KSF_NoModifiers } } },
    { Key::Equal, KTF_Shift, { { Key::Equal, KSF_Shift } } },
    { Key::Ins, KTF_NoFlags, { { Key::Ins, KSF_NoModifiers } } },
    { Key::Del, KTF_NoFlags, { { Key::Del, KSF_NoModifiers } } },
    { Key::Home, KTF_NoFlags, { { Key::Home, KSF_NoModifiers } } },
    { Key::End, KTF_NoFlags, { { Key::End, KSF_NoModifiers } } },
    { Key::PageUp, KTF_NoFlags, { { Key::PageUp, KSF_NoModifiers } } },
    { Key::PageDown, KTF_NoFlags, { { Key::PageDown, KSF_NoModifiers } } },
    { Key::A, KTF_NoFlags, { { Key::A, KSF_NoModifiers } }, "a.wav" },
    { Key::A, KTF_Shift, { { Key::A, KSF_Shift } }, "a.wav" },
    { Key::A, KTF_Alt, { { Key::A, KSF_NoModifiers } }, "aa.wav" },
    { Key::B, KTF_NoFlags, { { Key::B, KSF_NoModifiers } }, "b.wav" },
    { Key::B, KTF_Shift, { { Key::B, KSF_Shift } }, "b.wav" },
    { Key::C, KTF_NoFlags, { { Key::C, KSF_NoModifiers } }, "c.wav" },
    { Key::C, KTF_Shift, { { Key::C, KSF_Shift } }, "c.wav" },
    { Key::C, KTF_Ctrl, { { Key::C } }, "k.wav" },  // Not a mistake: Ctrl+C should give 'c' with sound 'k'
    { Key::D, KTF_NoFlags, { { Key::D, KSF_NoModifiers } }, "d.wav" },
    { Key::D, KTF_Shift, { { Key::D, KSF_Shift } }, "d.wav" },
    { Key::D, KTF_Ctrl, { { Key::D } }, "t.wav" },  // Not a mistake: Ctrl+D should give 'd' with sound 't'
    { Key::E, KTF_NoFlags, { { Key::E, KSF_NoModifiers } }, "e.wav" },
    { Key::E, KTF_Shift, { { Key::E, KSF_Shift } }, "e.wav" },
    { Key::E, KTF_Alt, { { Key::E, KSF_NoModifiers } }, "ee.wav" },
    { Key::E, KTF_Ctrl, { { Key::E } }, "u.wav" },  // Not a mistake: Ctrl+E should give 'e' with sound 'u'
    { Key::F, KTF_NoFlags, { { Key::F, KSF_NoModifiers } }, "f.wav" },
    { Key::F, KTF_Shift, { { Key::F, KSF_Shift } }, "f.wav" },
    { Key::G, KTF_NoFlags, { { Key::G, KSF_NoModifiers } }, "g.wav" },
    { Key::G, KTF_Shift, { { Key::G, KSF_Shift } }, "g.wav" },
    { Key::H, KTF_NoFlags, { { Key::H, KSF_NoModifiers } }, "h.wav" },
    { Key::H, KTF_Shift, { { Key::H, KSF_Shift } }, "h.wav" },
    { Key::I, KTF_NoFlags, { { Key::I, KSF_NoModifiers } }, "i.wav" },
    { Key::I, KTF_Shift, { { Key::I, KSF_Shift } }, "i.wav" },
    { Key::I, KTF_Alt, { { Key::I, KSF_NoModifiers } }, "ie.wav" },
    { Key::I, KTF_Ctrl, { { Key::I } }, "u.wav" },  // Not a mistake: Ctrl+I should give 'i' with sound 'u'
    { Key::J, KTF_NoFlags, { { Key::J, KSF_NoModifiers } }, "j.wav" },
    { Key::J, KTF_Shift, { { Key::J, KSF_Shift } }, "j.wav" },
    { Key::K, KTF_NoFlags, { { Key::K, KSF_NoModifiers } }, "k.wav" },
    { Key::K, KTF_Shift, { { Key::K, KSF_Shift } }, "k.wav" },
    { Key::L, KTF_NoFlags, { { Key::L, KSF_NoModifiers } }, "l.wav" },
    { Key::L, KTF_Shift, { { Key::L, KSF_Shift } }, "l.wav" },
    { Key::M, KTF_NoFlags, { { Key::M, KSF_NoModifiers } }, "m.wav" },
    { Key::M, KTF_Shift, { { Key::M, KSF_Shift } }, "m.wav" },
    { Key::N, KTF_NoFlags, { { Key::N, KSF_NoModifiers } }, "n.wav" },
    { Key::N, KTF_Shift, { { Key::N, KSF_Shift } }, "n.wav" },
    { Key::O, KTF_NoFlags, { { Key::O, KSF_NoModifiers } }, "o.wav" },
    { Key::O, KTF_Shift, { { Key::O, KSF_Shift } }, "o.wav" },
    { Key::O, KTF_Alt, { { Key::O, KSF_NoModifiers } }, "oo.wav" },
    { Key::P, KTF_NoFlags, { { Key::P, KSF_NoModifiers } }, "p.wav" },
    { Key::P, KTF_Shift, { { Key::P, KSF_Shift } }, "p.wav" },
    { Key::Q, KTF_NoFlags, { { Key::Q, KSF_NoModifiers } }, "q.wav" },
    { Key::Q, KTF_Shift, { { Key::Q, KSF_Shift } }, "q.wav" },
    { Key::R, KTF_NoFlags, { { Key::R, KSF_NoModifiers } }, "r.wav" },
    { Key::R, KTF_Shift, { { Key::R, KSF_Shift } }, "r.wav" },
    { Key::S, KTF_NoFlags, { { Key::S, KSF_NoModifiers } }, "s.wav" },
    { Key::S, KTF_Shift, { { Key::S, KSF_Shift } }, "s.wav" },
    { Key::T, KTF_NoFlags, { { Key::T, KSF_NoModifiers } }, "t.wav" },
    { Key::T, KTF_Shift, { { Key::T, KSF_Shift } }, "t.wav" },
    { Key::U, KTF_NoFlags, { { Key::U, KSF_NoModifiers } }, "u.wav" },
    { Key::U, KTF_Shift, { { Key::U, KSF_Shift } }, "u.wav" },
    { Key::U, KTF_Alt, { { Key::U, KSF_NoModifiers } }, "uu.wav" },
    { Key::V, KTF_NoFlags, { { Key::V, KSF_NoModifiers } }, "v.wav" },
    { Key::V, KTF_Shift, { { Key::V, KSF_Shift } }, "v.wav" },
    { Key::W, KTF_NoFlags, { { Key::W, KSF_NoModifiers } }, "w.wav" },
    { Key::W, KTF_Shift, { { Key::W, KSF_Shift } }, "w.wav" },
    { Key::X, KTF_NoFlags, { { Key::X, KSF_NoModifiers } }, "x.wav" },
    { Key::X, KTF_Shift, { { Key::X, KSF_Shift } }, "x.wav" },
    { Key::Y, KTF_NoFlags, { { Key::Y, KSF_NoModifiers } }, "y.wav" },
    { Key::Y, KTF_Shift, { { Key::Y, KSF_Shift } }, "y.wav" },
    { Key::Y, KTF_Ctrl, { { Key::Y } }, "i.wav" },  // Not a mistake: Ctrl+Y should give 'y' with sound 'i'
    { Key::Y, KTF_Alt, { { Key::Y } }, "j.wav" },
    { Key::Z, KTF_NoFlags, { { Key::Z, KSF_NoModifiers } }, "z.wav" },
    { Key::Z, KTF_Shift, { { Key::Z, KSF_Shift } }, "z.wav" },
    { Key::X, KTF_Ctrl, { { Key::X, KSF_Ctrl } } },
    { Key::V, KTF_Ctrl, { { Key::V, KSF_Ctrl } } },
    { Key::Z, KTF_Ctrl, { { Key::Z, KSF_Ctrl } } },
    { Key::A, KTF_Ctrl, { { Key::A, KSF_Ctrl } } },
    { Key::F, KTF_Ctrl, { { Key::F, KSF_Ctrl } } },
    { Key::Tab, KTF_Alt, { { Key::Tab, KSF_Alt } } },
    { Key::F4, KTF_Alt, { { Key::F4, KSF_Alt } } },
};

static const std::vector<KeyTranslationEntry> g_dutchClassic = {
    { Key::Esc, KTF_NoFlags, { { Key::Esc, KSF_NoModifiers } } },
    { Key::CapsLock, KTF_NoFlags, { { Key::CapsLock, KSF_NoModifiers } } },
    { Key::Up, KTF_NoFlags, { { Key::Up, KSF_NoModifiers } } },
    { Key::Down, KTF_NoFlags, { { Key::Down, KSF_NoModifiers } } },
    { Key::Left, KTF_NoFlags, { { Key::Left, KSF_NoModifiers } } },
    { Key::Right, KTF_NoFlags, { { Key::Right, KSF_NoModifiers } } },
    { Key::Backspace, KTF_NoFlags, { { Key::Backspace, KSF_NoModifiers } } },
    { Key::Space, KTF_NoFlags, { { Key::Space, KSF_NoModifiers } } },
    { Key::Enter, KTF_NoFlags, { { Key::Enter, KSF_NoModifiers } } },
    { Key::Tab, KTF_NoFlags, { { Key::Tab, KSF_NoModifiers } } },
    { Key::Dot, KTF_NoFlags, { { Key::Dot, KSF_NoModifiers } }, std::string(), true },
    { Key::Dot, KTF_Shift, { { Key::Dot, KSF_Shift } } },
    { Key::Comma, KTF_NoFlags, { { Key::Comma, KSF_NoModifiers } } },
    { Key::Comma, KTF_Shift, { { Key::Comma, KSF_Shift } } },
    { Key::One, KTF_NoFlags, { { Key::A }, { Key::A } }, "aa.wav" },
    { Key::Two, KTF_NoFlags, { { Key::U }, { Key::U } }, "uu.wav" },
    { Key::Three, KTF_NoFlags, { { Key::O }, { Key::O } }, "oo.wav" },
    { Key::Four, KTF_NoFlags, { { Key::E }, { Key::E } }, "ee.wav" },
    { Key::Five, KTF_NoFlags, { { Key::E }, { Key::U } }, "eu.wav" },
    { Key::Six, KTF_NoFlags, { { Key::A }, { Key::U } }, "au.wav" },
    { Key::Seven, KTF_NoFlags, { { Key::U }, { Key::I } }, "ui.wav" },
    { Key::Eight, KTF_NoFlags, { { Key::I }, { Key::E } }, "ie.wav" },
    { Key::Nine, KTF_NoFlags, { { Key::O }, { Key::E } }, "oe.wav" },
    { Key::Zero, KTF_NoFlags, { { Key::E }, { Key::I } }, "ei.wav" },
    { Key::One, KTF_Ctrl, { { Key::One, KSF_NoModifiers } }, "1.wav" },
    { Key::Two, KTF_Ctrl, { { Key::Two, KSF_NoModifiers } }, "2.wav" },
    { Key::Three, KTF_Ctrl, { { Key::Three, KSF_NoModifiers } }, "3.wav" },
    { Key::Four, KTF_Ctrl, { { Key::Four, KSF_NoModifiers } }, "4.wav" },
    { Key::Five, KTF_Ctrl, { { Key::Five, KSF_NoModifiers } }, "5.wav" },
    { Key::Six, KTF_Ctrl, { { Key::Six, KSF_NoModifiers } }, "6.wav" },
    { Key::Seven, KTF_Ctrl, { { Key::Seven, KSF_NoModifiers } }, "7.wav" },
    { Key::Eight, KTF_Ctrl, { { Key::Eight, KSF_NoModifiers } }, "8.wav" },
    { Key::Nine, KTF_Ctrl, { { Key::Nine, KSF_NoModifiers } }, "9.wav" },
    { Key::Zero, KTF_Ctrl, { { Key::Zero, KSF_NoModifiers } }, "0.wav" },
    { Key::One, KTF_Shift, { { Key::One, KSF_Shift } }, std::string(), true },
    { Key::Two, KTF_Shift, { { Key::Two, KSF_Shift } } },
    { Key::Three, KTF_Shift, { { Key::Three, KSF_Shift } } },
    { Key::Four, KTF_Shift, { { Key::Four, KSF_Shift } } },
    { Key::Five, KTF_Shift, { { Key::Five, KSF_Shift } } },
    //{ Key::Six, KTF_Shift, { { Key::Six, KSF_Shift } } },
    { Key::Seven, KTF_Shift, { { Key::Seven, KSF_Shift } } },
    { Key::Eight, KTF_Shift, { { Key::Eight, KSF_Shift } } },
    { Key::Nine, KTF_Shift, { { Key::Nine, KSF_Shift } } },
    { Key::Zero, KTF_Shift, { { Key::Zero, KSF_Shift } } },
    { Key::Five, KTF_Ctrl | KTF_Alt, { { Key::Five, KSF_Ctrl | KSF_Alt } } },  // Euro sign
    { Key::AltGr, KTF_NoFlags, { { Key::E }, { Key::E }, { Key::R } }, "eer.wav" },
    { Key::AltGr, KTF_Ctrl, { { Key::E }, { Key::E }, { Key::R } }, "eer.wav" },  // In non-US keyboard layouts, Windows translates AltGr to LeftCtrl+AltGr
    { Key::OpenBracket, KTF_NoFlags, { { Key::O }, { Key::U } }, "ou.wav" },
    { Key::CloseBracket, KTF_NoFlags, { { Key::I }, { Key::J } }, "ij.wav" },
    { Key::CloseBracket, KTF_Ctrl, { { Key::I }, { Key::J } }, "u.wav" },  // Not a mistake: Ctrl+] should give 'ij' with sound 'u'
    { Key::OpenBracket, KTF_Shift, { { Key::OpenBracket, KSF_Shift } } },
    { Key::CloseBracket, KTF_Shift, { { Key::CloseBracket, KSF_Shift} } },
    { Key::Semicolon, KTF_NoFlags, { { Key::N }, { Key::G } }, "ng.wav" },
    { Key::Semicolon, KTF_Ctrl, { { Key::Semicolon, KSF_NoModifiers } } },
    { Key::Semicolon, KTF_Shift, { { Key::Semicolon, KSF_Shift } } },
    { Key::Apostrophe, KTF_NoFlags, { { Key::N }, { Key::K } }, "nk.wav" },
    { Key::Apostrophe, KTF_Ctrl, { { Key::Apostrophe, KSF_NoModifiers } } },
    { Key::Apostrophe, KTF_Shift, { { Key::Apostrophe, KSF_Shift } } },
    { Key::Backslash, KTF_NoFlags, { { Key::C }, { Key::H } }, "ch.wav" },
    { Key::Backslash, KTF_Ctrl, { { Key::C }, { Key::H } }, "sj.wav" },  // Not a mistake: Ctrl+\ should give 'ch' with sound 'sj'
    { Key::Backslash, KTF_Shift, { { Key::Backslash, KSF_Shift } } },
    { Key::Minus, KTF_NoFlags, { { Key::E }, { Key::U }, { Key::R } }, "eur.wav" },
    { Key::Minus, KTF_Ctrl, { { Key::Minus, KSF_NoModifiers } } },
    { Key::Minus, KTF_Shift, { { Key::Minus, KSF_Shift } } },
    { Key::Slash, KTF_NoFlags, { { Key::O }, { Key::O }, { Key::R } }, "oor.wav" },
    { Key::Slash, KTF_Ctrl, { { Key::Slash, KSF_NoModifiers } } },
    { Key::Slash, KTF_Shift, { { Key::Slash, KSF_Shift } }, std::string(), true },
    { Key::Equal, KTF_NoFlags, { { Key::S }, { Key::C }, { Key::H } }, "sch.wav" },
    { Key::Equal, KTF_Ctrl, { { Key::Equal, KSF_NoModifiers } } },
    { Key::Equal, KTF_Shift, { { Key::Equal, KSF_Shift } } },
    { Key::Ins, KTF_NoFlags, { { Key::A }, { Key::A }, { Key::I } }, "aai.wav" },
    { Key::Ins, KTF_Ctrl, { { Key::Ins, KSF_NoModifiers } } },
    { Key::Del, KTF_NoFlags, { { Key::E }, { Key::E }, { Key::U }, { Key::W } }, "eeuw.wav" },
    { Key::Del, KTF_Ctrl, { { Key::Del, KSF_NoModifiers } } },
    { Key::Home, KTF_NoFlags, { { Key::O }, { Key::O }, { Key::I } }, "ooi.wav" },
    { Key::Home, KTF_Ctrl, { { Key::Home, KSF_NoModifiers } } },
    { Key::End, KTF_NoFlags, { { Key::I }, { Key::E }, { Key::U }, { Key::W } }, "ieuw.wav" },
    { Key::End, KTF_Ctrl, { { Key::End, KSF_NoModifiers } } },
    { Key::PageUp, KTF_NoFlags, { { Key::O }, { Key::E }, { Key::I } }, "oei.wav" },
    { Key::PageUp, KTF_Ctrl, { { Key::PageUp, KSF_NoModifiers } } },
    { Key::PageDown, KTF_NoFlags, { { Key::U }, { Key::W } }, "uw.wav" },
    { Key::PageDown, KTF_Ctrl, { { Key::PageDown, KSF_NoModifiers } } },
    { Key::A, KTF_NoFlags, { { Key::A, KSF_NoModifiers } }, "a.wav" },
    { Key::A, KTF_Shift, { { Key::A, KSF_Shift } }, "a.wav" },
    { Key::A, KTF_Alt, { { Key::A, KSF_NoModifiers } }, "aa.wav" },
    { Key::B, KTF_NoFlags, { { Key::B, KSF_NoModifiers } }, "b.wav" },
    { Key::B, KTF_Shift, { { Key::B, KSF_Shift } }, "b.wav" },
    { Key::C, KTF_NoFlags, { { Key::C, KSF_NoModifiers } }, "c.wav" },
    { Key::C, KTF_Shift, { { Key::C, KSF_Shift } }, "c.wav" },
    { Key::C, KTF_Ctrl, { { Key::C } }, "k.wav" },  // Not a mistake: Ctrl+C should give 'c' with sound 'k'
    { Key::D, KTF_NoFlags, { { Key::D, KSF_NoModifiers } }, "d.wav" },
    { Key::D, KTF_Shift, { { Key::D, KSF_Shift } }, "d.wav" },
    { Key::D, KTF_Ctrl, { { Key::D } }, "t.wav" },  // Not a mistake: Ctrl+D should give 'd' with sound 't'
    { Key::E, KTF_NoFlags, { { Key::E, KSF_NoModifiers } }, "e.wav" },
    { Key::E, KTF_Shift, { { Key::E, KSF_Shift } }, "e.wav" },
    { Key::E, KTF_Alt, { { Key::E, KSF_NoModifiers } }, "ee.wav" },
    { Key::E, KTF_Ctrl, { { Key::E } }, "u.wav" },  // Not a mistake: Ctrl+E should give 'e' with sound 'u'
    { Key::F, KTF_NoFlags, { { Key::F, KSF_NoModifiers } }, "f.wav" },
    { Key::F, KTF_Shift, { { Key::F, KSF_Shift } }, "f.wav" },
    { Key::G, KTF_NoFlags, { { Key::G, KSF_NoModifiers } }, "g.wav" },
    { Key::G, KTF_Shift, { { Key::G, KSF_Shift } }, "g.wav" },
    { Key::H, KTF_NoFlags, { { Key::H, KSF_NoModifiers } }, "h.wav" },
    { Key::H, KTF_Shift, { { Key::H, KSF_Shift } }, "h.wav" },
    { Key::I, KTF_NoFlags, { { Key::I, KSF_NoModifiers } }, "i.wav" },
    { Key::I, KTF_Shift, { { Key::I, KSF_Shift } }, "i.wav" },
    { Key::I, KTF_Alt, { { Key::I, KSF_NoModifiers } }, "ie.wav" },
    { Key::I, KTF_Ctrl, { { Key::I } }, "u.wav" },  // Not a mistake: Ctrl+I should give 'i' with sound 'u'
    { Key::J, KTF_NoFlags, { { Key::J, KSF_NoModifiers } }, "j.wav" },
    { Key::J, KTF_Shift, { { Key::J, KSF_Shift } }, "j.wav" },
    { Key::K, KTF_NoFlags, { { Key::K, KSF_NoModifiers } }, "k.wav" },
    { Key::K, KTF_Shift, { { Key::K, KSF_Shift } }, "k.wav" },
    { Key::L, KTF_NoFlags, { { Key::L, KSF_NoModifiers } }, "l.wav" },
    { Key::L, KTF_Shift, { { Key::L, KSF_Shift } }, "l.wav" },
    { Key::M, KTF_NoFlags, { { Key::M, KSF_NoModifiers } }, "m.wav" },
    { Key::M, KTF_Shift, { { Key::M, KSF_Shift } }, "m.wav" },
    { Key::N, KTF_NoFlags, { { Key::N, KSF_NoModifiers } }, "n.wav" },
    { Key::N, KTF_Shift, { { Key::N, KSF_Shift } }, "n.wav" },
    { Key::O, KTF_NoFlags, { { Key::O, KSF_NoModifiers } }, "o.wav" },
    { Key::O, KTF_Shift, { { Key::O, KSF_Shift } }, "o.wav" },
    { Key::O, KTF_Alt, { { Key::O, KSF_NoModifiers } }, "oo.wav" },
    { Key::P, KTF_NoFlags, { { Key::P, KSF_NoModifiers } }, "p.wav" },
    { Key::P, KTF_Shift, { { Key::P, KSF_Shift } }, "p.wav" },
    { Key::Q, KTF_NoFlags, { { Key::Q, KSF_NoModifiers } }, "q.wav" },
    { Key::Q, KTF_Shift, { { Key::Q, KSF_Shift } }, "q.wav" },
    { Key::R, KTF_NoFlags, { { Key::R, KSF_NoModifiers } }, "r.wav" },
    { Key::R, KTF_Shift, { { Key::R, KSF_Shift } }, "r.wav" },
    { Key::S, KTF_NoFlags, { { Key::S, KSF_NoModifiers } }, "s.wav" },
    { Key::S, KTF_Shift, { { Key::S, KSF_Shift } }, "s.wav" },
    { Key::T, KTF_NoFlags, { { Key::T, KSF_NoModifiers } }, "t.wav" },
    { Key::T, KTF_Shift, { { Key::T, KSF_Shift } }, "t.wav" },
    { Key::U, KTF_NoFlags, { { Key::U, KSF_NoModifiers } }, "u.wav" },
    { Key::U, KTF_Shift, { { Key::U, KSF_Shift } }, "u.wav" },
    { Key::U, KTF_Alt, { { Key::U, KSF_NoModifiers } }, "uu.wav" },
    { Key::V, KTF_NoFlags, { { Key::V, KSF_NoModifiers } }, "v.wav" },
    { Key::V, KTF_Shift, { { Key::V, KSF_Shift } }, "v.wav" },
    { Key::W, KTF_NoFlags, { { Key::W, KSF_NoModifiers } }, "w.wav" },
    { Key::W, KTF_Shift, { { Key::W, KSF_Shift } }, "w.wav" },
    { Key::X, KTF_NoFlags, { { Key::X, KSF_NoModifiers } }, "x.wav" },
    { Key::X, KTF_Shift, { { Key::X, KSF_Shift } }, "x.wav" },
    { Key::Y, KTF_NoFlags, { { Key::Y, KSF_NoModifiers } }, "y.wav" },
    { Key::Y, KTF_Shift, { { Key::Y, KSF_Shift } }, "y.wav" },
    { Key::Y, KTF_Ctrl, { { Key::Y } }, "i.wav" },  // Not a mistake: Ctrl+Y should give 'y' with sound 'i'
    { Key::Y, KTF_Alt, { { Key::Y } }, "j.wav" },
    { Key::Z, KTF_NoFlags, { { Key::Z, KSF_NoModifiers } }, "z.wav" },
    { Key::Z, KTF_Shift, { { Key::Z, KSF_Shift } }, "z.wav" },
    { Key::X, KTF_Ctrl, { { Key::X, KSF_Ctrl } } },
    { Key::V, KTF_Ctrl, { { Key::V, KSF_Ctrl } } },
    { Key::Z, KTF_Ctrl, { { Key::Z, KSF_Ctrl } } },
    { Key::A, KTF_Ctrl, { { Key::A, KSF_Ctrl } } },
    { Key::F, KTF_Ctrl, { { Key::F, KSF_Ctrl } } },
    { Key::Tab, KTF_Alt, { { Key::Tab, KSF_Alt } } },
    { Key::F4, KTF_Alt, { { Key::F4, KSF_Alt } } },
};

static const std::vector<KeyTranslationEntry> g_dutchKWeC = {
    { Key::Esc, KTF_NoFlags, { { Key::Esc, KSF_NoModifiers } } },
    { Key::CapsLock, KTF_NoFlags, { { Key::CapsLock, KSF_NoModifiers } } },
    { Key::Up, KTF_NoFlags, { { Key::Up, KSF_NoModifiers } } },
    { Key::Down, KTF_NoFlags, { { Key::Down, KSF_NoModifiers } } },
    { Key::Left, KTF_NoFlags, { { Key::Left, KSF_NoModifiers } } },
    { Key::Right, KTF_NoFlags, { { Key::Right, KSF_NoModifiers } } },
    { Key::Backspace, KTF_NoFlags, { { Key::Backspace, KSF_NoModifiers } } },
    { Key::Space, KTF_NoFlags, { { Key::Space, KSF_NoModifiers } } },
    { Key::Enter, KTF_NoFlags, { { Key::Enter, KSF_NoModifiers } } },
    { Key::Tab, KTF_NoFlags, { { Key::Tab, KSF_NoModifiers } } },
    { Key::Dot, KTF_NoFlags, { { Key::Dot, KSF_NoModifiers } }, std::string(), true },
    { Key::Dot, KTF_Shift, { { Key::Dot, KSF_Shift } } },
    { Key::Comma, KTF_NoFlags, { { Key::Comma, KSF_NoModifiers } } },
    { Key::Comma, KTF_Shift, { { Key::Comma, KSF_Shift } } },
    { Key::One, KTF_NoFlags, { { Key::A }, { Key::A } }, "aa.wav" },
    { Key::Two, KTF_NoFlags, { { Key::E }, { Key::E } }, "ee.wav" },
    { Key::Three, KTF_NoFlags, { { Key::O }, { Key::O } }, "oo.wav" },
    { Key::Four, KTF_NoFlags, { { Key::U }, { Key::U } }, "uu.wav" },
    { Key::Five, KTF_NoFlags, { { Key::A }, { Key::U } }, "au.wav" },
    { Key::Six, KTF_NoFlags, { { Key::E }, { Key::I } }, "ei.wav" },
    { Key::Seven, KTF_NoFlags, { { Key::E }, { Key::U } }, "eu.wav" },
    { Key::Eight, KTF_NoFlags, { { Key::I }, { Key::E } }, "ie.wav" },
    { Key::Nine, KTF_NoFlags, { { Key::I }, { Key::J } }, "ij.wav" },
    { Key::Zero, KTF_NoFlags, { { Key::O }, { Key::E } }, "oe.wav" },
    { Key::One, KTF_Ctrl, { { Key::One, KSF_NoModifiers } }, "1.wav" },
    { Key::Two, KTF_Ctrl, { { Key::Two, KSF_NoModifiers } }, "2.wav" },
    { Key::Three, KTF_Ctrl, { { Key::Three, KSF_NoModifiers } }, "3.wav" },
    { Key::Four, KTF_Ctrl, { { Key::Four, KSF_NoModifiers } }, "4.wav" },
    { Key::Five, KTF_Ctrl, { { Key::Five, KSF_NoModifiers } }, "5.wav" },
    { Key::Six, KTF_Ctrl, { { Key::Six, KSF_NoModifiers } }, "6.wav" },
    { Key::Seven, KTF_Ctrl, { { Key::Seven, KSF_NoModifiers } }, "7.wav" },
    { Key::Eight, KTF_Ctrl, { { Key::Eight, KSF_NoModifiers } }, "8.wav" },
    { Key::Nine, KTF_Ctrl, { { Key::Nine, KSF_NoModifiers } }, "9.wav" },
    { Key::Zero, KTF_Ctrl, { { Key::Zero, KSF_NoModifiers } }, "0.wav" },
    { Key::One, KTF_Shift, { { Key::One, KSF_Shift } }, std::string(), true },
    { Key::Two, KTF_Shift, { { Key::Two, KSF_Shift } } },
    { Key::Three, KTF_Shift, { { Key::Three, KSF_Shift } } },
    { Key::Four, KTF_Shift, { { Key::Four, KSF_Shift } } },
    { Key::Five, KTF_Shift, { { Key::Five, KSF_Shift } } },
    //{ Key::Six, KTF_Shift, { { Key::Six, KSF_Shift } } },
    { Key::Seven, KTF_Shift, { { Key::Seven, KSF_Shift } } },
    { Key::Eight, KTF_Shift, { { Key::Eight, KSF_Shift } } },
    { Key::Nine, KTF_Shift, { { Key::Nine, KSF_Shift } } },
    { Key::Zero, KTF_Shift, { { Key::Zero, KSF_Shift } } },
    { Key::Five, KTF_Ctrl | KTF_Alt, { { Key::Five, KSF_Ctrl | KSF_Alt } } },  // Euro sign
    { Key::AltGr, KTF_NoFlags, { { Key::E }, { Key::E }, { Key::R } }, "eer.wav" },
    { Key::AltGr, KTF_Ctrl, { { Key::E }, { Key::E }, { Key::R } }, "eer.wav" },  // In non-US keyboard layouts, Windows translates AltGr to LeftCtrl+AltGr
    { Key::OpenBracket, KTF_NoFlags, { { Key::O }, { Key::U } }, "ou.wav" },
    { Key::CloseBracket, KTF_NoFlags, { { Key::U }, { Key::I } }, "ui.wav" },
    { Key::OpenBracket, KTF_Ctrl, { { Key::OpenBracket, KSF_NoModifiers } } },
    { Key::CloseBracket, KTF_Ctrl, { { Key::CloseBracket, KSF_NoModifiers } } },
    { Key::OpenBracket, KTF_Shift, { { Key::OpenBracket, KSF_Shift } } },
    { Key::CloseBracket, KTF_Shift, { { Key::CloseBracket, KSF_Shift} } },
    { Key::Semicolon, KTF_NoFlags, { { Key::N }, { Key::G } }, "ng.wav" },
    { Key::Semicolon, KTF_Ctrl, { { Key::Semicolon, KSF_NoModifiers } } },
    { Key::Semicolon, KTF_Shift, { { Key::Semicolon, KSF_Shift } } },
    { Key::Apostrophe, KTF_NoFlags, { { Key::N }, { Key::K } }, "nk.wav" },
    { Key::Apostrophe, KTF_Ctrl, { { Key::Apostrophe, KSF_NoModifiers } } },
    { Key::Apostrophe, KTF_Shift, { { Key::Apostrophe, KSF_Shift } } },
    { Key::Backslash, KTF_NoFlags, { { Key::C }, { Key::H } }, "ch.wav" },
    { Key::Backslash, KTF_Ctrl, { { Key::C }, { Key::H } }, "sj.wav" },  // Not a mistake: Ctrl+\ should give 'ch' with sound 'sj'
    { Key::Backslash, KTF_Shift, { { Key::Backslash, KSF_Shift } } },
    { Key::Minus, KTF_NoFlags, { { Key::E }, { Key::U }, { Key::R } }, "eur.wav" },
    { Key::Minus, KTF_Ctrl, { { Key::Minus, KSF_NoModifiers } } },
    { Key::Minus, KTF_Shift, { { Key::Minus, KSF_Shift } } },
    { Key::Slash, KTF_NoFlags, { { Key::O }, { Key::O }, { Key::R } }, "oor.wav" },
    { Key::Slash, KTF_Ctrl, { { Key::Slash, KSF_NoModifiers } } },
    { Key::Slash, KTF_Shift, { { Key::Slash, KSF_Shift } }, std::string(), true },
    { Key::Equal, KTF_NoFlags, { { Key::S }, { Key::C }, { Key::H } }, "sch.wav" },
    { Key::Equal, KTF_Ctrl, { { Key::Equal, KSF_NoModifiers } } },
    { Key::Equal, KTF_Shift, { { Key::Equal, KSF_Shift } } },
    { Key::Ins, KTF_NoFlags, { { Key::A }, { Key::A }, { Key::I } }, "aai.wav" },
    { Key::Ins, KTF_Ctrl, { { Key::Ins, KSF_NoModifiers } } },
    { Key::Del, KTF_NoFlags, { { Key::E }, { Key::E }, { Key::U }, { Key::W } }, "eeuw.wav" },
    { Key::Del, KTF_Ctrl, { { Key::Del, KSF_NoModifiers } } },
    { Key::Home, KTF_NoFlags, { { Key::O }, { Key::O }, { Key::I } }, "ooi.wav" },
    { Key::Home, KTF_Ctrl, { { Key::Home, KSF_NoModifiers } } },
    { Key::End, KTF_NoFlags, { { Key::I }, { Key::E }, { Key::U }, { Key::W } }, "ieuw.wav" },
    { Key::End, KTF_Ctrl, { { Key::End, KSF_NoModifiers } } },
    { Key::PageUp, KTF_NoFlags, { { Key::O }, { Key::E }, { Key::I } }, "oei.wav" },
    { Key::PageUp, KTF_Ctrl, { { Key::PageUp, KSF_NoModifiers } } },
    { Key::PageDown, KTF_NoFlags, { { Key::U }, { Key::W } }, "uw.wav" },
    { Key::PageDown, KTF_Ctrl, { { Key::PageDown, KSF_NoModifiers } } },
    { Key::A, KTF_NoFlags, { { Key::A, KSF_NoModifiers } }, "a.wav" },
    { Key::A, KTF_Shift, { { Key::A, KSF_Shift } }, "a.wav" },
    { Key::A, KTF_Alt, { { Key::A, KSF_NoModifiers } }, "aa.wav" },
    { Key::B, KTF_NoFlags, { { Key::B, KSF_NoModifiers } }, "b.wav" },
    { Key::B, KTF_Shift, { { Key::B, KSF_Shift } }, "b.wav" },
    { Key::C, KTF_NoFlags, { { Key::C, KSF_NoModifiers } }, "c.wav" },
    { Key::C, KTF_Shift, { { Key::C, KSF_Shift } }, "c.wav" },
    { Key::C, KTF_Ctrl, { { Key::C } }, "k.wav" },  // Not a mistake: Ctrl+C should give 'c' with sound 'k'
    { Key::D, KTF_NoFlags, { { Key::D, KSF_NoModifiers } }, "d.wav" },
    { Key::D, KTF_Shift, { { Key::D, KSF_Shift } }, "d.wav" },
    { Key::D, KTF_Ctrl, { { Key::D } }, "t.wav" },  // Not a mistake: Ctrl+D should give 'd' with sound 't'
    { Key::E, KTF_NoFlags, { { Key::E, KSF_NoModifiers } }, "e.wav" },
    { Key::E, KTF_Shift, { { Key::E, KSF_Shift } }, "e.wav" },
    { Key::E, KTF_Alt, { { Key::E, KSF_NoModifiers } }, "ee.wav" },
    { Key::E, KTF_Ctrl, { { Key::E } }, "u.wav" },  // Not a mistake: Ctrl+E should give 'e' with sound 'u'
    { Key::F, KTF_NoFlags, { { Key::F, KSF_NoModifiers } }, "f.wav" },
    { Key::F, KTF_Shift, { { Key::F, KSF_Shift } }, "f.wav" },
    { Key::G, KTF_NoFlags, { { Key::G, KSF_NoModifiers } }, "g.wav" },
    { Key::G, KTF_Shift, { { Key::G, KSF_Shift } }, "g.wav" },
    { Key::H, KTF_NoFlags, { { Key::H, KSF_NoModifiers } }, "h.wav" },
    { Key::H, KTF_Shift, { { Key::H, KSF_Shift } }, "h.wav" },
    { Key::I, KTF_NoFlags, { { Key::I, KSF_NoModifiers } }, "i.wav" },
    { Key::I, KTF_Shift, { { Key::I, KSF_Shift } }, "i.wav" },
    { Key::I, KTF_Alt, { { Key::I, KSF_NoModifiers } }, "ie.wav" },
    { Key::I, KTF_Ctrl, { { Key::I } }, "u.wav" },  // Not a mistake: Ctrl+I should give 'i' with sound 'u'
    { Key::J, KTF_NoFlags, { { Key::J, KSF_NoModifiers } }, "j.wav" },
    { Key::J, KTF_Shift, { { Key::J, KSF_Shift } }, "j.wav" },
    { Key::K, KTF_NoFlags, { { Key::K, KSF_NoModifiers } }, "k.wav" },
    { Key::K, KTF_Shift, { { Key::K, KSF_Shift } }, "k.wav" },
    { Key::L, KTF_NoFlags, { { Key::L, KSF_NoModifiers } }, "l.wav" },
    { Key::L, KTF_Shift, { { Key::L, KSF_Shift } }, "l.wav" },
    { Key::M, KTF_NoFlags, { { Key::M, KSF_NoModifiers } }, "m.wav" },
    { Key::M, KTF_Shift, { { Key::M, KSF_Shift } }, "m.wav" },
    { Key::N, KTF_NoFlags, { { Key::N, KSF_NoModifiers } }, "n.wav" },
    { Key::N, KTF_Shift, { { Key::N, KSF_Shift } }, "n.wav" },
    { Key::O, KTF_NoFlags, { { Key::O, KSF_NoModifiers } }, "o.wav" },
    { Key::O, KTF_Shift, { { Key::O, KSF_Shift } }, "o.wav" },
    { Key::O, KTF_Alt, { { Key::O, KSF_NoModifiers } }, "oo.wav" },
    { Key::P, KTF_NoFlags, { { Key::P, KSF_NoModifiers } }, "p.wav" },
    { Key::P, KTF_Shift, { { Key::P, KSF_Shift } }, "p.wav" },
    { Key::Q, KTF_NoFlags, { { Key::Q, KSF_NoModifiers } }, "q.wav" },
    { Key::Q, KTF_Shift, { { Key::Q, KSF_Shift } }, "q.wav" },
    { Key::R, KTF_NoFlags, { { Key::R, KSF_NoModifiers } }, "r.wav" },
    { Key::R, KTF_Shift, { { Key::R, KSF_Shift } }, "r.wav" },
    { Key::S, KTF_NoFlags, { { Key::S, KSF_NoModifiers } }, "s.wav" },
    { Key::S, KTF_Shift, { { Key::S, KSF_Shift } }, "s.wav" },
    { Key::T, KTF_NoFlags, { { Key::T, KSF_NoModifiers } }, "t.wav" },
    { Key::T, KTF_Shift, { { Key::T, KSF_Shift } }, "t.wav" },
    { Key::U, KTF_NoFlags, { { Key::U, KSF_NoModifiers } }, "u.wav" },
    { Key::U, KTF_Shift, { { Key::U, KSF_Shift } }, "u.wav" },
    { Key::U, KTF_Alt, { { Key::U, KSF_NoModifiers } }, "uu.wav" },
    { Key::V, KTF_NoFlags, { { Key::V, KSF_NoModifiers } }, "v.wav" },
    { Key::V, KTF_Shift, { { Key::V, KSF_Shift } }, "v.wav" },
    { Key::W, KTF_NoFlags, { { Key::W, KSF_NoModifiers } }, "w.wav" },
    { Key::W, KTF_Shift, { { Key::W, KSF_Shift } }, "w.wav" },
    { Key::X, KTF_NoFlags, { { Key::X, KSF_NoModifiers } }, "x.wav" },
    { Key::X, KTF_Shift, { { Key::X, KSF_Shift } }, "x.wav" },
    { Key::Y, KTF_NoFlags, { { Key::Y, KSF_NoModifiers } }, "y.wav" },
    { Key::Y, KTF_Shift, { { Key::Y, KSF_Shift } }, "y.wav" },
    { Key::Y, KTF_Ctrl, { { Key::Y } }, "i.wav" },  // Not a mistake: Ctrl+Y should give 'y' with sound 'i'
    { Key::Y, KTF_Alt, { { Key::Y } }, "j.wav" },
    { Key::Z, KTF_NoFlags, { { Key::Z, KSF_NoModifiers } }, "z.wav" },
    { Key::Z, KTF_Shift, { { Key::Z, KSF_Shift } }, "z.wav" },
    { Key::X, KTF_Ctrl, { { Key::X, KSF_Ctrl } } },
    { Key::V, KTF_Ctrl, { { Key::V, KSF_Ctrl } } },
    { Key::Z, KTF_Ctrl, { { Key::Z, KSF_Ctrl } } },
    { Key::A, KTF_Ctrl, { { Key::A, KSF_Ctrl } } },
    { Key::F, KTF_Ctrl, { { Key::F, KSF_Ctrl } } },
    { Key::Tab, KTF_Alt, { { Key::Tab, KSF_Alt } } },
    { Key::F4, KTF_Alt, { { Key::F4, KSF_Alt } } },
};
#elif defined __LANGUAGE_NL_BE__
static const std::vector<KeyTranslationEntry> g_flemishDefault = {
    { Key::Esc, KTF_NoFlags, { { Key::Esc, KSF_NoModifiers } } },
    { Key::CapsLock, KTF_NoFlags, { { Key::CapsLock, KSF_NoModifiers } } },
    { Key::Up, KTF_NoFlags, { { Key::Up, KSF_NoModifiers } } },
    { Key::Down, KTF_NoFlags, { { Key::Down, KSF_NoModifiers } } },
    { Key::Left, KTF_NoFlags, { { Key::Left, KSF_NoModifiers } } },
    { Key::Right, KTF_NoFlags, { { Key::Right, KSF_NoModifiers } } },
    { Key::Backspace, KTF_NoFlags, { { Key::Backspace, KSF_NoModifiers } } },
    { Key::Space, KTF_NoFlags, { { Key::Space, KSF_NoModifiers } } },
    { Key::Enter, KTF_NoFlags, { { Key::Enter, KSF_NoModifiers } } },
    { Key::Tab, KTF_NoFlags, { { Key::Tab, KSF_NoModifiers } } },
    { Key::One, KTF_NoFlags, { { Key::One, KSF_NoModifiers } }, std::string(), false, CapsLock::Inactive },
    { Key::Two, KTF_NoFlags, { { Key::Two, KSF_NoModifiers } }, std::string(), false, CapsLock::Inactive },
    { Key::Three, KTF_NoFlags, { { Key::Three, KSF_NoModifiers } }, std::string(), false, CapsLock::Inactive },
    { Key::Four, KTF_NoFlags, { { Key::Four, KSF_NoModifiers } }, std::string(), false, CapsLock::Inactive },
    { Key::Five, KTF_NoFlags, { { Key::Five, KSF_NoModifiers } }, std::string(), false, CapsLock::Inactive },
    { Key::Six, KTF_NoFlags, { { Key::Six, KSF_NoModifiers } }, std::string(), false, CapsLock::Inactive },
    { Key::Seven, KTF_NoFlags, { { Key::Seven, KSF_NoModifiers } }, std::string(), false, CapsLock::Inactive },
    { Key::Eight, KTF_NoFlags, { { Key::Eight, KSF_NoModifiers } }, std::string(), true, CapsLock::Inactive },
    { Key::Nine, KTF_NoFlags, { { Key::Nine, KSF_NoModifiers } }, std::string(), false, CapsLock::Inactive },
    { Key::Zero, KTF_NoFlags, { { Key::Zero, KSF_NoModifiers } }, std::string(), false, CapsLock::Inactive },
    { Key::One, KTF_Shift, { { Key::One, KSF_Shift } }, "1.wav", false, CapsLock::Inactive },
    { Key::Two, KTF_Shift, { { Key::Two, KSF_Shift } }, "2.wav", false, CapsLock::Inactive },
    { Key::Three, KTF_Shift, { { Key::Three, KSF_Shift } }, "3.wav", false, CapsLock::Inactive },
    { Key::Four, KTF_Shift, { { Key::Four, KSF_Shift } }, "4.wav", false, CapsLock::Inactive },
    { Key::Five, KTF_Shift, { { Key::Five, KSF_Shift } }, "5.wav", false, CapsLock::Inactive },
    { Key::Six, KTF_Shift, { { Key::Six, KSF_Shift } }, "6.wav", false, CapsLock::Inactive },
    { Key::Seven, KTF_Shift, { { Key::Seven, KSF_Shift } }, "7.wav", false, CapsLock::Inactive },
    { Key::Eight, KTF_Shift, { { Key::Eight, KSF_Shift } }, "8.wav", false, CapsLock::Inactive },
    { Key::Nine, KTF_Shift, { { Key::Nine, KSF_Shift } }, "9.wav", false, CapsLock::Inactive },
    { Key::Zero, KTF_Shift, { { Key::Zero, KSF_Shift } }, "0.wav", false, CapsLock::Inactive },
    { Key::One, KTF_NoFlags, { { Key::One, KSF_NoModifiers } }, "1.wav", false, CapsLock::Active },
    { Key::Two, KTF_NoFlags, { { Key::Two, KSF_NoModifiers } }, "2.wav", false, CapsLock::Active },
    { Key::Three, KTF_NoFlags, { { Key::Three, KSF_NoModifiers } }, "3.wav", false, CapsLock::Active },
    { Key::Four, KTF_NoFlags, { { Key::Four, KSF_NoModifiers } }, "4.wav", false, CapsLock::Active },
    { Key::Five, KTF_NoFlags, { { Key::Five, KSF_NoModifiers } }, "5.wav", false, CapsLock::Active },
    { Key::Six, KTF_NoFlags, { { Key::Six, KSF_NoModifiers } }, "6.wav", false, CapsLock::Active },
    { Key::Seven, KTF_NoFlags, { { Key::Seven, KSF_NoModifiers } }, "7.wav", false, CapsLock::Active },
    { Key::Eight, KTF_NoFlags, { { Key::Eight, KSF_NoModifiers } }, "8.wav", false, CapsLock::Active },
    { Key::Nine, KTF_NoFlags, { { Key::Nine, KSF_NoModifiers } }, "9.wav", false, CapsLock::Active },
    { Key::Zero, KTF_NoFlags, { { Key::Zero, KSF_NoModifiers } }, "0.wav", false, CapsLock::Active },
    { Key::One, KTF_Shift, { { Key::One, KSF_Shift } }, std::string(), false, CapsLock::Active },
    { Key::Two, KTF_Shift, { { Key::Two, KSF_Shift } }, std::string(), false, CapsLock::Active },
    { Key::Three, KTF_Shift, { { Key::Three, KSF_Shift } }, std::string(), false, CapsLock::Active },
    { Key::Four, KTF_Shift, { { Key::Four, KSF_Shift } }, std::string(), false, CapsLock::Active },
    { Key::Five, KTF_Shift, { { Key::Five, KSF_Shift } }, std::string(), false, CapsLock::Active },
    { Key::Six, KTF_Shift, { { Key::Six, KSF_Shift } }, std::string(), false, CapsLock::Active },
    { Key::Seven, KTF_Shift, { { Key::Seven, KSF_Shift } }, std::string(), false, CapsLock::Active },
    { Key::Eight, KTF_Shift, { { Key::Eight, KSF_Shift } }, std::string(), true, CapsLock::Active },
    { Key::Nine, KTF_Shift, { { Key::Nine, KSF_Shift } }, std::string(), false, CapsLock::Active },
    { Key::Zero, KTF_Shift, { { Key::Zero, KSF_Shift } }, std::string(), false, CapsLock::Active },
    { Key::Semicolon, KTF_NoFlags, { { Key::Semicolon, KSF_NoModifiers } } },
    { Key::Semicolon, KTF_Shift, { { Key::Semicolon, KSF_Shift } } },
    { Key::CloseBracket, KTF_NoFlags, { { Key::CloseBracket, KSF_NoModifiers } } },
    { Key::CloseBracket, KTF_Shift, { { Key::CloseBracket, KSF_Shift } } },
    { Key::Comma, KTF_NoFlags, { { Key::Comma, KSF_NoModifiers } }, std::string(), false, CapsLock::Inactive },
    { Key::Comma, KTF_Shift, { { Key::Comma, KSF_Shift } }, std::string(), true, CapsLock::Inactive },
    { Key::Comma, KTF_NoFlags, { { Key::Comma, KSF_NoModifiers } }, std::string(), true, CapsLock::Active },
    { Key::Comma, KTF_Shift, { { Key::Comma, KSF_Shift } }, std::string(), false, CapsLock::Active },
    { Key::Dot, KTF_NoFlags, { { Key::Dot, KSF_NoModifiers } }, std::string(), false, CapsLock::Inactive },
    { Key::Dot, KTF_Shift, { { Key::Dot, KSF_Shift } }, std::string(), true, CapsLock::Inactive },
    { Key::Dot, KTF_NoFlags, { { Key::Dot, KSF_NoModifiers } }, std::string(), true, CapsLock::Active },
    { Key::Dot, KTF_Shift, { { Key::Dot, KSF_Shift } }, std::string(), false, CapsLock::Active },
    { Key::Slash, KTF_NoFlags, { { Key::Slash, KSF_NoModifiers } } },
    { Key::Slash, KTF_Shift, { { Key::Slash, KSF_Shift } } },
    { Key::Backtick, KTF_NoFlags, { { Key::Backtick, KSF_NoModifiers } } },
    { Key::Backtick, KTF_Shift, { { Key::Backtick, KSF_Shift } } },
    { Key::Backslash, KTF_NoFlags, { { Key::Backslash, KSF_NoModifiers } } },
    { Key::Backslash, KTF_Shift, { { Key::Backslash, KSF_Shift } } },
    { Key::AltGr, KTF_NoFlags, { { Key::E }, { Key::E }, { Key::R } }, "eer.wav" },
    { Key::AltGr, KTF_Ctrl, { { Key::E }, { Key::E }, { Key::R } }, "eer.wav" },  // In non-US keyboard layouts, Windows translates AltGr to LeftCtrl+AltGr
    { Key::Equal, KTF_NoFlags, { { Key::Equal, KSF_NoModifiers } } },
    { Key::Equal, KTF_Shift, { { Key::Equal, KSF_Shift } } },
    { Key::OpenBracket, KTF_NoFlags, { { Key::OpenBracket, KSF_NoModifiers } } },
    { Key::OpenBracket, KTF_Shift, { { Key::OpenBracket, KSF_Shift } } },
    { Key::Minus, KTF_NoFlags, { { Key::Minus, KSF_NoModifiers } } },
    { Key::Minus, KTF_Shift, { { Key::Minus, KSF_Shift } } },
    { Key::Ins, KTF_NoFlags, { { Key::Ins, KSF_NoModifiers } } },
    { Key::Ins, KTF_Shift, { { Key::Ins, KSF_Shift } } },
    { Key::Home, KTF_NoFlags, { { Key::Home, KSF_NoModifiers } } },
    { Key::Home, KTF_Shift, { { Key::Home, KSF_Shift } } },
    { Key::PageUp, KTF_NoFlags, { { Key::PageUp, KSF_NoModifiers } } },
    { Key::PageUp, KTF_Shift, { { Key::PageUp, KSF_Shift } } },
    { Key::Del, KTF_NoFlags, { { Key::Del, KSF_NoModifiers } } },
    { Key::Del, KTF_Shift, { { Key::Del, KSF_Shift } } },
    { Key::End, KTF_NoFlags, { { Key::End, KSF_NoModifiers } } },
    { Key::End, KTF_Shift, { { Key::End, KSF_Shift } } },
    { Key::PageDown, KTF_NoFlags, { { Key::PageDown, KSF_NoModifiers } } },
    { Key::PageDown, KTF_Shift, { { Key::PageDown, KSF_Shift } } },
    { Key::A, KTF_NoFlags, { { Key::A, KSF_NoModifiers } }, "a.wav" },
    { Key::A, KTF_Shift, { { Key::A, KSF_Shift } }, "a.wav" },
    { Key::B, KTF_NoFlags, { { Key::B, KSF_NoModifiers } }, "b.wav" },
    { Key::B, KTF_Shift, { { Key::B, KSF_Shift } }, "b.wav" },
    { Key::C, KTF_NoFlags, { { Key::C, KSF_NoModifiers } }, "c.wav" },
    { Key::C, KTF_Shift, { { Key::C, KSF_Shift } }, "c.wav" },
    { Key::D, KTF_NoFlags, { { Key::D, KSF_NoModifiers } }, "d.wav" },
    { Key::D, KTF_Shift, { { Key::D, KSF_Shift } }, "d.wav" },
    { Key::E, KTF_NoFlags, { { Key::E, KSF_NoModifiers } }, "e.wav" },
    { Key::E, KTF_Shift, { { Key::E, KSF_Shift } }, "e.wav" },
    { Key::F, KTF_NoFlags, { { Key::F, KSF_NoModifiers } }, "f.wav" },
    { Key::F, KTF_Shift, { { Key::F, KSF_Shift } }, "f.wav" },
    { Key::G, KTF_NoFlags, { { Key::G, KSF_NoModifiers } }, "g.wav" },
    { Key::G, KTF_Shift, { { Key::G, KSF_Shift } }, "g.wav" },
    { Key::H, KTF_NoFlags, { { Key::H, KSF_NoModifiers } }, "h.wav" },
    { Key::H, KTF_Shift, { { Key::H, KSF_Shift } }, "h.wav" },
    { Key::I, KTF_NoFlags, { { Key::I, KSF_NoModifiers } }, "i.wav" },
    { Key::I, KTF_Shift, { { Key::I, KSF_Shift } }, "i.wav" },
    { Key::J, KTF_NoFlags, { { Key::J, KSF_NoModifiers } }, "j.wav" },
    { Key::J, KTF_Shift, { { Key::J, KSF_Shift } }, "j.wav" },
    { Key::K, KTF_NoFlags, { { Key::K, KSF_NoModifiers } }, "k.wav" },
    { Key::K, KTF_Shift, { { Key::K, KSF_Shift } }, "k.wav" },
    { Key::L, KTF_NoFlags, { { Key::L, KSF_NoModifiers } }, "l.wav" },
    { Key::L, KTF_Shift, { { Key::L, KSF_Shift } }, "l.wav" },
    { Key::M, KTF_NoFlags, { { Key::M, KSF_NoModifiers } }, "m.wav" },
    { Key::M, KTF_Shift, { { Key::M, KSF_Shift } }, "m.wav" },
    { Key::N, KTF_NoFlags, { { Key::N, KSF_NoModifiers } }, "n.wav" },
    { Key::N, KTF_Shift, { { Key::N, KSF_Shift } }, "n.wav" },
    { Key::O, KTF_NoFlags, { { Key::O, KSF_NoModifiers } }, "o.wav" },
    { Key::O, KTF_Shift, { { Key::O, KSF_Shift } }, "o.wav" },
    { Key::P, KTF_NoFlags, { { Key::P, KSF_NoModifiers } }, "p.wav" },
    { Key::P, KTF_Shift, { { Key::P, KSF_Shift } }, "p.wav" },
    { Key::Q, KTF_NoFlags, { { Key::Q, KSF_NoModifiers } }, "q.wav" },
    { Key::Q, KTF_Shift, { { Key::Q, KSF_Shift } }, "q.wav" },
    { Key::R, KTF_NoFlags, { { Key::R, KSF_NoModifiers } }, "r.wav" },
    { Key::R, KTF_Shift, { { Key::R, KSF_Shift } }, "r.wav" },
    { Key::S, KTF_NoFlags, { { Key::S, KSF_NoModifiers } }, "s.wav" },
    { Key::S, KTF_Shift, { { Key::S, KSF_Shift } }, "s.wav" },
    { Key::T, KTF_NoFlags, { { Key::T, KSF_NoModifiers } }, "t.wav" },
    { Key::T, KTF_Shift, { { Key::T, KSF_Shift } }, "t.wav" },
    { Key::U, KTF_NoFlags, { { Key::U, KSF_NoModifiers } }, "u.wav" },
    { Key::U, KTF_Shift, { { Key::U, KSF_Shift } }, "u.wav" },
    { Key::V, KTF_NoFlags, { { Key::V, KSF_NoModifiers } }, "v.wav" },
    { Key::V, KTF_Shift, { { Key::V, KSF_Shift } }, "v.wav" },
    { Key::W, KTF_NoFlags, { { Key::W, KSF_NoModifiers } }, "w.wav" },
    { Key::W, KTF_Shift, { { Key::W, KSF_Shift } }, "w.wav" },
    { Key::X, KTF_NoFlags, { { Key::X, KSF_NoModifiers } }, "x.wav" },
    { Key::X, KTF_Shift, { { Key::X, KSF_Shift } }, "x.wav" },
    { Key::Y, KTF_NoFlags, { { Key::Y, KSF_NoModifiers } }, "y.wav" },
    { Key::Y, KTF_Shift, { { Key::Y, KSF_Shift } }, "y.wav" },
    { Key::Z, KTF_NoFlags, { { Key::Z, KSF_NoModifiers } }, "z.wav" },
    { Key::Z, KTF_Shift, { { Key::Z, KSF_Shift } }, "z.wav" },
};

static const std::vector<KeyTranslationEntry> g_flemishClassic = {
    { Key::Esc, KTF_NoFlags, { { Key::Esc, KSF_NoModifiers } } },
    { Key::CapsLock, KTF_NoFlags, { { Key::CapsLock, KSF_NoModifiers } } },
    { Key::Up, KTF_NoFlags, { { Key::Up, KSF_NoModifiers } } },
    { Key::Down, KTF_NoFlags, { { Key::Down, KSF_NoModifiers } } },
    { Key::Left, KTF_NoFlags, { { Key::Left, KSF_NoModifiers } } },
    { Key::Right, KTF_NoFlags, { { Key::Right, KSF_NoModifiers } } },
    { Key::Backspace, KTF_NoFlags, { { Key::Backspace, KSF_NoModifiers } } },
    { Key::Space, KTF_NoFlags, { { Key::Space, KSF_NoModifiers } } },
    { Key::Enter, KTF_NoFlags, { { Key::Enter, KSF_NoModifiers } } },
    { Key::Tab, KTF_NoFlags, { { Key::Tab, KSF_NoModifiers } } },
    { Key::One, KTF_NoFlags, { { Key::A }, { Key::A } }, "aa.wav", false, CapsLock::Inactive },
    { Key::Two, KTF_NoFlags, { { Key::U }, { Key::U } }, "uu.wav", false, CapsLock::Inactive },
    { Key::Three, KTF_NoFlags, { { Key::O }, { Key::O } }, "oo.wav", false, CapsLock::Inactive },
    { Key::Four, KTF_NoFlags, { { Key::E }, { Key::E } }, "ee.wav", false, CapsLock::Inactive },
    { Key::Five, KTF_NoFlags, { { Key::E }, { Key::U } }, "eu.wav", false, CapsLock::Inactive },
    { Key::Six, KTF_NoFlags, { { Key::A }, { Key::U } }, "au.wav", false, CapsLock::Inactive },
    { Key::Seven, KTF_NoFlags, { { Key::U }, { Key::I } }, "ui.wav", false, CapsLock::Inactive },
    { Key::Eight, KTF_NoFlags, { { Key::I }, { Key::E } }, "ie.wav", false, CapsLock::Inactive },
    { Key::Nine, KTF_NoFlags, { { Key::O }, { Key::E } }, "oe.wav", false, CapsLock::Inactive },
    { Key::Zero, KTF_NoFlags, { { Key::E }, { Key::I } }, "ij.wav", false, CapsLock::Inactive },
    { Key::One, KTF_Shift, { { Key::One, KSF_Shift } }, "1.wav", false, CapsLock::Inactive },
    { Key::Two, KTF_Shift, { { Key::Two, KSF_Shift } }, "2.wav", false, CapsLock::Inactive },
    { Key::Three, KTF_Shift, { { Key::Three, KSF_Shift } }, "3.wav", false, CapsLock::Inactive },
    { Key::Four, KTF_Shift, { { Key::Four, KSF_Shift } }, "4.wav", false, CapsLock::Inactive },
    { Key::Five, KTF_Shift, { { Key::Five, KSF_Shift } }, "5.wav", false, CapsLock::Inactive },
    { Key::Six, KTF_Shift, { { Key::Six, KSF_Shift } }, "6.wav", false, CapsLock::Inactive },
    { Key::Seven, KTF_Shift, { { Key::Seven, KSF_Shift } }, "7.wav", false, CapsLock::Inactive },
    { Key::Eight, KTF_Shift, { { Key::Eight, KSF_Shift } }, "8.wav", false, CapsLock::Inactive },
    { Key::Nine, KTF_Shift, { { Key::Nine, KSF_Shift } }, "9.wav", false, CapsLock::Inactive },
    { Key::Zero, KTF_Shift, { { Key::Zero, KSF_Shift } }, "0.wav", false, CapsLock::Inactive },
    { Key::One, KTF_Ctrl, { { Key::One, KSF_NoModifiers } }, std::string(), false, CapsLock::Inactive },
    { Key::Two, KTF_Ctrl, { { Key::Two, KSF_NoModifiers } }, std::string(), false, CapsLock::Inactive },
    { Key::Three, KTF_Ctrl, { { Key::Three, KSF_NoModifiers } }, std::string(), false, CapsLock::Inactive },
    { Key::Four, KTF_Ctrl, { { Key::Four, KSF_NoModifiers } }, std::string(), false, CapsLock::Inactive },
    { Key::Five, KTF_Ctrl, { { Key::Five, KSF_NoModifiers } }, std::string(), false, CapsLock::Inactive },
    { Key::Six, KTF_Ctrl, { { Key::Six, KSF_NoModifiers } }, std::string(), false, CapsLock::Inactive },
    { Key::Seven, KTF_Ctrl, { { Key::Seven, KSF_NoModifiers } }, std::string(), false, CapsLock::Inactive },
    { Key::Eight, KTF_Ctrl, { { Key::Eight, KSF_NoModifiers } }, std::string(), true, CapsLock::Inactive },
    { Key::Nine, KTF_Ctrl, { { Key::Nine, KSF_NoModifiers } }, std::string(), false, CapsLock::Inactive },
    { Key::Zero, KTF_Ctrl, { { Key::Zero, KSF_NoModifiers } }, std::string(), false, CapsLock::Inactive },
    { Key::One, KTF_NoFlags, { { Key::A }, { Key::A } }, "aa.wav", false, CapsLock::Active },
    { Key::Two, KTF_NoFlags, { { Key::U }, { Key::U } }, "uu.wav", false, CapsLock::Active },
    { Key::Three, KTF_NoFlags, { { Key::O }, { Key::O } }, "oo.wav", false, CapsLock::Active },
    { Key::Four, KTF_NoFlags, { { Key::E }, { Key::E } }, "ee.wav", false, CapsLock::Active },
    { Key::Five, KTF_NoFlags, { { Key::E }, { Key::U } }, "eu.wav", false, CapsLock::Active },
    { Key::Six, KTF_NoFlags, { { Key::A }, { Key::U } }, "au.wav", false, CapsLock::Active },
    { Key::Seven, KTF_NoFlags, { { Key::U }, { Key::I } }, "ui.wav", false, CapsLock::Active },
    { Key::Eight, KTF_NoFlags, { { Key::I }, { Key::E } }, "ie.wav", false, CapsLock::Active },
    { Key::Nine, KTF_NoFlags, { { Key::O }, { Key::E } }, "oe.wav", false, CapsLock::Active },
    { Key::Zero, KTF_NoFlags, { { Key::E }, { Key::I } }, "ij.wav", false, CapsLock::Active },
    { Key::One, KTF_Shift, { { Key::One, KSF_Shift } }, std::string(), false, CapsLock::Active },
    { Key::Two, KTF_Shift, { { Key::Two, KSF_Shift } }, std::string(), false, CapsLock::Active },
    { Key::Three, KTF_Shift, { { Key::Three, KSF_Shift } }, std::string(), false, CapsLock::Active },
    { Key::Four, KTF_Shift, { { Key::Four, KSF_Shift } }, std::string(), false, CapsLock::Active },
    { Key::Five, KTF_Shift, { { Key::Five, KSF_Shift } }, std::string(), false, CapsLock::Active },
    { Key::Six, KTF_Shift, { { Key::Six, KSF_Shift } }, std::string(), false, CapsLock::Active },
    { Key::Seven, KTF_Shift, { { Key::Seven, KSF_Shift } }, std::string(), false, CapsLock::Active },
    { Key::Eight, KTF_Shift, { { Key::Eight, KSF_Shift } }, std::string(), true, CapsLock::Active },
    { Key::Nine, KTF_Shift, { { Key::Nine, KSF_Shift } }, std::string(), false, CapsLock::Active },
    { Key::Zero, KTF_Shift, { { Key::Zero, KSF_Shift } }, std::string(), false, CapsLock::Active },
    { Key::Semicolon, KTF_NoFlags, { { Key::I }, { Key::J } }, "ij.wav" },
    { Key::CloseBracket, KTF_NoFlags, { { Key::O }, { Key::U } }, "ou.wav" },
    { Key::Semicolon, KTF_Shift, { { Key::Semicolon, KSF_Shift } } },
    { Key::CloseBracket, KTF_Shift, { { Key::CloseBracket, KSF_Shift } } },
    { Key::Semicolon, KTF_Ctrl, { { Key::I }, { Key::J } }, "u.wav" },
    { Key::CloseBracket, KTF_Ctrl, { { Key::CloseBracket, KSF_NoModifiers } } },
    { Key::Comma, KTF_NoFlags, { { Key::Comma, KSF_NoModifiers } }, std::string(), false, CapsLock::Inactive },
    { Key::Comma, KTF_Shift, { { Key::Comma, KSF_Shift } }, std::string(), true, CapsLock::Inactive },
    { Key::Comma, KTF_NoFlags, { { Key::Comma, KSF_NoModifiers } }, std::string(), true, CapsLock::Active },
    { Key::Comma, KTF_Shift, { { Key::Comma, KSF_Shift } }, std::string(), false, CapsLock::Active },
    { Key::Dot, KTF_NoFlags, { { Key::Dot, KSF_NoModifiers } }, std::string(), false, CapsLock::Inactive },
    { Key::Dot, KTF_Shift, { { Key::Dot, KSF_Shift } }, std::string(), true, CapsLock::Inactive },
    { Key::Dot, KTF_NoFlags, { { Key::Dot, KSF_NoModifiers } }, std::string(), true, CapsLock::Active },
    { Key::Dot, KTF_Shift, { { Key::Dot, KSF_Shift } }, std::string(), false, CapsLock::Active },
    { Key::Slash, KTF_NoFlags, { { Key::N }, { Key::G } }, "ng.wav" },
    { Key::Slash, KTF_Shift, { { Key::Slash, KSF_Shift } } },
    { Key::Slash, KTF_Ctrl, { { Key::Slash, KSF_NoModifiers } } },
    { Key::Backtick, KTF_NoFlags, { { Key::N }, { Key::K } }, "nk.wav" },
    { Key::Backtick, KTF_Shift, { { Key::Backtick, KSF_Shift } } },
    { Key::Backtick, KTF_Ctrl, { { Key::Backtick, KSF_NoModifiers } } },
    { Key::Backslash, KTF_NoFlags, { { Key::C }, { Key::H } }, "ch.wav" },
    { Key::Backslash, KTF_Shift, { { Key::Backslash, KSF_Shift } } },
    { Key::Backslash, KTF_Ctrl, { { Key::C }, { Key::H } }, "sj.wav" },
    { Key::AltGr, KTF_NoFlags, { { Key::E }, { Key::E }, { Key::R } }, "eer.wav" },
    { Key::AltGr, KTF_Ctrl, { { Key::E }, { Key::E }, { Key::R } }, "eer.wav" },  // In non-US keyboard layouts, Windows translates AltGr to LeftCtrl+AltGr
    { Key::Equal, KTF_NoFlags, { { Key::O }, { Key::O }, { Key::R } }, "oor.wav" },
    { Key::Equal, KTF_Shift, { { Key::Equal, KSF_Shift } } },
    { Key::Equal, KTF_Ctrl, { { Key::Equal, KSF_NoModifiers } } },
    { Key::OpenBracket, KTF_NoFlags, { { Key::E }, { Key::U }, { Key::R } }, "eur.wav" },
    { Key::OpenBracket, KTF_Shift, { { Key::OpenBracket, KSF_Shift } } },
    { Key::OpenBracket, KTF_Ctrl, { { Key::OpenBracket, KSF_NoModifiers } } },
    { Key::Minus, KTF_NoFlags, { { Key::S }, { Key::C }, { Key::H } }, "sch.wav" },
    { Key::Minus, KTF_Shift, { { Key::Minus, KSF_Shift } } },
    { Key::Minus, KTF_Ctrl, { { Key::Minus, KSF_NoModifiers } } },
    { Key::Ins, KTF_NoFlags, { { Key::A }, { Key::A }, { Key::I } }, "aai.wav" },
    { Key::Ins, KTF_Shift, { { Key::Ins, KSF_Shift } } },
    { Key::Ins, KTF_Ctrl, { { Key::Ins, KSF_NoModifiers } } },
    { Key::Home, KTF_NoFlags, { { Key::O }, { Key::O }, { Key::I } }, "ooi.wav" },
    { Key::Home, KTF_Shift, { { Key::Home, KSF_Shift } } },
    { Key::Home, KTF_Ctrl, { { Key::Home, KSF_NoModifiers } } },
    { Key::PageUp, KTF_NoFlags, { { Key::O }, { Key::E }, { Key::I } }, "oei.wav" },
    { Key::PageUp, KTF_Shift, { { Key::PageUp, KSF_Shift } } },
    { Key::PageUp, KTF_Ctrl, { { Key::PageUp, KSF_NoModifiers } } },
    { Key::Del, KTF_NoFlags, { { Key::E }, { Key::E }, { Key::U }, { Key::W } }, "eeuw.wav" },
    { Key::Del, KTF_Shift, { { Key::Del, KSF_Shift } } },
    { Key::Del, KTF_Ctrl, { { Key::Del, KSF_NoModifiers } } },
    { Key::End, KTF_NoFlags, { { Key::I }, { Key::E }, { Key::U }, { Key::W } }, "ieuw.wav" },
    { Key::End, KTF_Shift, { { Key::End, KSF_Shift } } },
    { Key::End, KTF_Ctrl, { { Key::End, KSF_NoModifiers } } },
    { Key::PageDown, KTF_NoFlags, { { Key::U }, { Key::W } }, "uw.wav" },
    { Key::PageDown, KTF_Shift, { { Key::PageDown, KSF_Shift } } },
    { Key::PageDown, KTF_Ctrl, { { Key::PageDown, KSF_NoModifiers } } },
    { Key::A, KTF_NoFlags, { { Key::A, KSF_NoModifiers } }, "a.wav" },
    { Key::A, KTF_Shift, { { Key::A, KSF_Shift } }, "a.wav" },
    { Key::A, KTF_Alt, { { Key::A, KSF_NoModifiers } }, "aa.wav" },
    { Key::B, KTF_NoFlags, { { Key::B, KSF_NoModifiers } }, "b.wav" },
    { Key::B, KTF_Shift, { { Key::B, KSF_Shift } }, "b.wav" },
    { Key::C, KTF_NoFlags, { { Key::C, KSF_NoModifiers } }, "c.wav" },
    { Key::C, KTF_Shift, { { Key::C, KSF_Shift } }, "c.wav" },
    { Key::C, KTF_Ctrl, { { Key::C } }, "k.wav" },  // Not a mistake: Ctrl+C should give 'c' with sound 'k'
    { Key::D, KTF_NoFlags, { { Key::D, KSF_NoModifiers } }, "d.wav" },
    { Key::D, KTF_Shift, { { Key::D, KSF_Shift } }, "d.wav" },
    { Key::D, KTF_Ctrl, { { Key::D } }, "t.wav" },  // Not a mistake: Ctrl+D should give 'd' with sound 't'
    { Key::E, KTF_NoFlags, { { Key::E, KSF_NoModifiers } }, "e.wav" },
    { Key::E, KTF_Shift, { { Key::E, KSF_Shift } }, "e.wav" },
    { Key::E, KTF_Alt, { { Key::E, KSF_NoModifiers } }, "ee.wav" },
    { Key::E, KTF_Ctrl, { { Key::E } }, "u.wav" },  // Not a mistake: Ctrl+E should give 'e' with sound 'u'
    { Key::F, KTF_NoFlags, { { Key::F, KSF_NoModifiers } }, "f.wav" },
    { Key::F, KTF_Shift, { { Key::F, KSF_Shift } }, "f.wav" },
    { Key::G, KTF_NoFlags, { { Key::G, KSF_NoModifiers } }, "g.wav" },
    { Key::G, KTF_Shift, { { Key::G, KSF_Shift } }, "g.wav" },
    { Key::H, KTF_NoFlags, { { Key::H, KSF_NoModifiers } }, "h.wav" },
    { Key::H, KTF_Shift, { { Key::H, KSF_Shift } }, "h.wav" },
    { Key::I, KTF_NoFlags, { { Key::I, KSF_NoModifiers } }, "i.wav" },
    { Key::I, KTF_Shift, { { Key::I, KSF_Shift } }, "i.wav" },
    { Key::I, KTF_Alt, { { Key::I, KSF_NoModifiers } }, "ie.wav" },
    { Key::I, KTF_Ctrl, { { Key::I } }, "u.wav" },  // Not a mistake: Ctrl+I should give 'i' with sound 'u'
    { Key::J, KTF_NoFlags, { { Key::J, KSF_NoModifiers } }, "j.wav" },
    { Key::J, KTF_Shift, { { Key::J, KSF_Shift } }, "j.wav" },
    { Key::K, KTF_NoFlags, { { Key::K, KSF_NoModifiers } }, "k.wav" },
    { Key::K, KTF_Shift, { { Key::K, KSF_Shift } }, "k.wav" },
    { Key::L, KTF_NoFlags, { { Key::L, KSF_NoModifiers } }, "l.wav" },
    { Key::L, KTF_Shift, { { Key::L, KSF_Shift } }, "l.wav" },
    { Key::M, KTF_NoFlags, { { Key::M, KSF_NoModifiers } }, "m.wav" },
    { Key::M, KTF_Shift, { { Key::M, KSF_Shift } }, "m.wav" },
    { Key::N, KTF_NoFlags, { { Key::N, KSF_NoModifiers } }, "n.wav" },
    { Key::N, KTF_Shift, { { Key::N, KSF_Shift } }, "n.wav" },
    { Key::O, KTF_NoFlags, { { Key::O, KSF_NoModifiers } }, "o.wav" },
    { Key::O, KTF_Shift, { { Key::O, KSF_Shift } }, "o.wav" },
    { Key::O, KTF_Alt, { { Key::O, KSF_NoModifiers } }, "oo.wav" },
    { Key::P, KTF_NoFlags, { { Key::P, KSF_NoModifiers } }, "p.wav" },
    { Key::P, KTF_Shift, { { Key::P, KSF_Shift } }, "p.wav" },
    { Key::Q, KTF_NoFlags, { { Key::Q, KSF_NoModifiers } }, "q.wav" },
    { Key::Q, KTF_Shift, { { Key::Q, KSF_Shift } }, "q.wav" },
    { Key::R, KTF_NoFlags, { { Key::R, KSF_NoModifiers } }, "r.wav" },
    { Key::R, KTF_Shift, { { Key::R, KSF_Shift } }, "r.wav" },
    { Key::S, KTF_NoFlags, { { Key::S, KSF_NoModifiers } }, "s.wav" },
    { Key::S, KTF_Shift, { { Key::S, KSF_Shift } }, "s.wav" },
    { Key::T, KTF_NoFlags, { { Key::T, KSF_NoModifiers } }, "t.wav" },
    { Key::T, KTF_Shift, { { Key::T, KSF_Shift } }, "t.wav" },
    { Key::U, KTF_NoFlags, { { Key::U, KSF_NoModifiers } }, "u.wav" },
    { Key::U, KTF_Shift, { { Key::U, KSF_Shift } }, "u.wav" },
    { Key::U, KTF_Alt, { { Key::U, KSF_NoModifiers } }, "uu.wav" },
    { Key::V, KTF_NoFlags, { { Key::V, KSF_NoModifiers } }, "v.wav" },
    { Key::V, KTF_Shift, { { Key::V, KSF_Shift } }, "v.wav" },
    { Key::W, KTF_NoFlags, { { Key::W, KSF_NoModifiers } }, "w.wav" },
    { Key::W, KTF_Shift, { { Key::W, KSF_Shift } }, "w.wav" },
    { Key::X, KTF_NoFlags, { { Key::X, KSF_NoModifiers } }, "x.wav" },
    { Key::X, KTF_Shift, { { Key::X, KSF_Shift } }, "x.wav" },
    { Key::Y, KTF_NoFlags, { { Key::Y, KSF_NoModifiers } }, "y.wav" },
    { Key::Y, KTF_Shift, { { Key::Y, KSF_Shift } }, "y.wav" },
    { Key::Y, KTF_Ctrl, { { Key::Y } }, "i.wav" },  // Not a mistake: Ctrl+Y should give 'y' with sound 'i'
    { Key::Y, KTF_Alt, { { Key::Y } }, "j.wav" },
    { Key::Z, KTF_NoFlags, { { Key::Z, KSF_NoModifiers } }, "z.wav" },
    { Key::Z, KTF_Shift, { { Key::Z, KSF_Shift } }, "z.wav" },
};
#endif

KeyTranslation FindTranslation(const std::vector<KeyTranslationEntry>& entries, Key key, bool caps, bool shift, bool ctrl, bool alt)
{
    CapsLock capsLock = caps ? CapsLock::Active : CapsLock::Inactive;

    for (const KeyTranslationEntry& entry : entries)
    {
        if (entry.input == key && (entry.capsLock == CapsLock::Ignore || entry.capsLock == capsLock) && entry.shift == shift && entry.ctrl == ctrl && entry.alt == alt)
        {
            KeyTranslation kt;
            kt.keystrokes = entry.output;
            kt.sound = entry.sound;
            kt.speak_sentence = entry.speak_sentence;
            return kt;
        }
    }

    return KeyTranslation();
}

KeyTranslation TranslateKey(Key key, bool caps, bool shift, bool ctrl, bool alt, Layout layout)
{
    switch (layout)
    {
#if defined __LANGUAGE_NL__
    case Layout::Default:
        return FindTranslation(g_dutchDefault, key, caps, shift, ctrl, alt);
    case Layout::Classic:
        return FindTranslation(g_dutchClassic, key, caps, shift, ctrl, alt);
    case Layout::KWeC:
        return FindTranslation(g_dutchKWeC, key, caps, shift, ctrl, alt);
#elif defined __LANGUAGE_NL_BE__
    case Layout::Default:
        return FindTranslation(g_flemishDefault, key, caps, shift, ctrl, alt);
    case Layout::Classic:
        return FindTranslation(g_flemishClassic, key, caps, shift, ctrl, alt);
#endif
    default:
        return KeyTranslation();
    }
}
